

# This file was *autogenerated* from the file ecdh.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9739 = Integer(9739); _sage_const_497 = Integer(497); _sage_const_1768 = Integer(1768); _sage_const_1804 = Integer(1804); _sage_const_5368 = Integer(5368); _sage_const_815 = Integer(815); _sage_const_3190 = Integer(3190); _sage_const_1829 = Integer(1829); _sage_const_0 = Integer(0)# ECDLP is the problem of finding an integer $n$ such that $Q = [n]P$.



# Like encountered with the discrete logarithm problem, scalar multiplcationof a point in $E(f_p$ seems to be a hard problem to undo with the most efficient algorithm running $q^{1/2}$ time when $P$ generates a subgroup of size $q$


# This makes it a great candidate for a trapdoor function.




# Define the finite field
p = _sage_const_9739 
F = GF(p)

# Define the elliptic curve
E = EllipticCurve(F, [_sage_const_497 , _sage_const_1768 ])

# Define the generator point G
G = E(_sage_const_1804 , _sage_const_5368 )

# Define Alice's public key QA
QA = E(_sage_const_815 , _sage_const_3190 )

# Define Bob's secret key nB
nB = _sage_const_1829 

# Calculate the shared secret S = [nB]QA
S = nB * QA

print(f"Shared secret S: {S}")

# Extract the x-coordinate of S
x_coord = S[_sage_const_0 ]

# Convert the x-coordinate to a string
x_coord_str = str(x_coord)

# Calculate the SHA1 hash of the x-coordinate
import hashlib
hash_object = hashlib.sha1(x_coord_str.encode())
hex_dig = hash_object.hexdigest()

# Format the answer
answer = f"crypto{{{hex_dig}}}"
print(f"Answer: {answer}")

