

# This file was *autogenerated* from the file sol.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6277101735386680763835789423176059013767194773182842284081 = Integer(6277101735386680763835789423176059013767194773182842284081); _sage_const_0xa37abc6c431f9ac398bf5bd1aa6678320ace8ecb93d23f2a = Integer(0xa37abc6c431f9ac398bf5bd1aa6678320ace8ecb93d23f2a); _sage_const_0xc3ddfa6bca8ad15a72d8ca32a5a576155da4ddaa43b1f0aa = Integer(0xc3ddfa6bca8ad15a72d8ca32a5a576155da4ddaa43b1f0aa); _sage_const_236894979676116967369153264540878706747091303513 = Integer(236894979676116967369153264540878706747091303513); _sage_const_0x2fa1f92d1ecce92014771993cc14899d4b5977883397edde = Integer(0x2fa1f92d1ecce92014771993cc14899d4b5977883397edde); _sage_const_0x7d86b77b5d1d45ebaf226a52d77a62f7afbaafa80c002961 = Integer(0x7d86b77b5d1d45ebaf226a52d77a62f7afbaafa80c002961); _sage_const_873865316854725788202849324608451680951850980105 = Integer(873865316854725788202849324608451680951850980105); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_96 = Integer(96)
order = _sage_const_6277101735386680763835789423176059013767194773182842284081  

r1 = _sage_const_0xa37abc6c431f9ac398bf5bd1aa6678320ace8ecb93d23f2a 

s1 = _sage_const_0xc3ddfa6bca8ad15a72d8ca32a5a576155da4ddaa43b1f0aa 

s1_inv = inverse_mod(s1, order)

z1 = _sage_const_236894979676116967369153264540878706747091303513 

r2 = _sage_const_0x2fa1f92d1ecce92014771993cc14899d4b5977883397edde 

s2 = _sage_const_0x7d86b77b5d1d45ebaf226a52d77a62f7afbaafa80c002961 

s2_inv = inverse_mod(s2, order)

z2 = _sage_const_873865316854725788202849324608451680951850980105 


matrix = [[order, _sage_const_0 , _sage_const_0 , _sage_const_0 ], [_sage_const_0 , order, _sage_const_0 , _sage_const_0 ],

[r1*s1_inv, r2*s2_inv, (_sage_const_2 **_sage_const_96 ) / order, _sage_const_0 ],

[z1*s1_inv, z2*s2_inv, _sage_const_0 , _sage_const_2 **_sage_const_96 ]]

sol = Matrix(matrix).LLL()

r1_inv = inverse_mod(r1, order)

row = sol[_sage_const_2 ]

potential_nonce_1 = (row[_sage_const_0 ])%order

potential_priv_key = (r1_inv * ((potential_nonce_1 * s1) - z1))%order

print("the secret is: ",potential_priv_key)

